INFO     root:log_util.py:16 接口用例数据：[2.0, 'articleId有误，更新失败', 'http://39.100.104.214:8080', '/update/', 'put', '{"userid":${userid}, "token": "${token}", "articleId":1234, "title":"python", "content":"test test"}', '"code": "03"', '', '', '']
INFO     root:log_util.py:16 请求原始数据：{"userid":${userid}, "token": "${token}", "articleId":1234, "title":"python", "content":"test test"}
INFO     root:log_util.py:16 请求数据预处理结果：{"userid":337, "token": "e951750fd86bfe9d643d46b42fa2f1c7", "articleId":1234, "title":"python", "content":"test test"}
INFO     root:log_util.py:16 接口调用成功！
INFO     root:log_util.py:16 响应数据：{"articleId": 1234, "code": "03", "userid": 337}
INFO     root:log_util.py:16 无关联参数提取..
INFO     root:log_util.py:16 【"code": "03"】关键字断言成功【{"articleId": 1234, "code": "03", "userid": 337}】